name: Shell comand

on: [push]

jobs:
  run-shell-command:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hellow world"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    environment: test
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Directory powerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
